import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--text-primary)",
        secondary: "var(--text-secondary)",
        tertiary: "var(--text-tertiary)",
        inverse: "var(--text-inverse)",
        surface: {
          bg: "var(--surface-bg)",
          card: "var(--surface-card)",
          hover: "var(--surface-card-hover)",
          elevated: "var(--surface-elevated)",
        },
        brand: {
          primary: 'var(--brand-primary)',
          'primary-hover': 'var(--brand-primary-hover)',
          'primary-bg': 'var(--brand-primary-bg)',
        },
        fcgreen: {
          100: "#dcfce7",
          500: "#22c55e",
          600: "#16a34a",
          700: "#15803d",
        },
        action: {
          primary: 'var(--action-primary)',
          'primary-hover': 'var(--action-primary-hover)',
          secondary: 'var(--action-secondary)',
          'secondary-hover': 'var(--action-secondary-hover)',
          ghost: 'var(--action-ghost)',
          'ghost-hover': 'var(--action-ghost-hover)',
          disabled: 'var(--action-disabled)',
        },
        border: {
          DEFAULT: 'var(--border-default)',
          default: 'var(--border-default)',
          subtle: 'var(--border-subtle)',
          focus: 'var(--border-focus)',
        },
        divider: {
          DEFAULT: 'var(--divider-default)',
          default: 'var(--divider-default)',
          subtle: 'var(--divider-subtle)',
        },
        feedback: {
          success: 'var(--color-success)',
          'success-bg': 'var(--color-success-bg)',
          'success-border': 'var(--color-success-border)',
          warning: 'var(--color-warning)',
          'warning-bg': 'var(--color-warning-bg)',
          'warning-border': 'var(--color-warning-border)',
          error: 'var(--color-error)',
          'error-bg': 'var(--color-error-bg)',
          'error-border': 'var(--color-error-border)',
        },
        'red-team': {
          DEFAULT: 'var(--color-red-team)',
          bg: 'var(--color-red-team-bg)',
          border: 'var(--color-red-team-border)',
        },
        'blue-team': {
          DEFAULT: 'var(--color-blue-team)',
          bg: 'var(--color-blue-team-bg)',
          border: 'var(--color-blue-team-border)',
        },
        // 축구 게임 메타포
        condition: {
          best: 'var(--condition-best)',
          good: 'var(--condition-good)',
          normal: 'var(--condition-normal)',
          poor: 'var(--condition-poor)',
          worst: 'var(--condition-worst)',
        },
        tier: {
          bronze: 'var(--tier-bronze)',
          'bronze-bg': 'var(--tier-bronze-bg)',
          'bronze-from': 'var(--tier-bronze-from)',
          'bronze-via': 'var(--tier-bronze-via)',
          'bronze-to': 'var(--tier-bronze-to)',
          'bronze-border': 'var(--tier-bronze-border)',
          'bronze-text': 'var(--tier-bronze-text)',
          'bronze-shadow': 'var(--tier-bronze-shadow)',
          silver: 'var(--tier-silver)',
          'silver-bg': 'var(--tier-silver-bg)',
          'silver-from': 'var(--tier-silver-from)',
          'silver-via': 'var(--tier-silver-via)',
          'silver-to': 'var(--tier-silver-to)',
          'silver-border': 'var(--tier-silver-border)',
          'silver-text': 'var(--tier-silver-text)',
          'silver-shadow': 'var(--tier-silver-shadow)',
          'silver-ring': 'var(--tier-silver-ring)',
          gold: 'var(--tier-gold)',
          'gold-bg': 'var(--tier-gold-bg)',
          'gold-from': 'var(--tier-gold-from)',
          'gold-via': 'var(--tier-gold-via)',
          'gold-to': 'var(--tier-gold-to)',
          'gold-border': 'var(--tier-gold-border)',
          'gold-text': 'var(--tier-gold-text)',
          'gold-shadow': 'var(--tier-gold-shadow)',
          'gold-ring': 'var(--tier-gold-ring)',
          special: 'var(--tier-special)',
          'special-bg': 'var(--tier-special-bg)',
        },
        event: {
          'training-bg': 'var(--event-training-bg)',
          'training-border': 'var(--event-training-border)',
          'training-text': 'var(--event-training-text)',
          'training-icon-bg': 'var(--event-training-icon-bg)',
          'training-icon-text': 'var(--event-training-icon-text)',
          'training-detail-border': 'var(--event-training-detail-border)',
          'training-meta-icon': 'var(--event-training-meta-icon)',
          'training-map-accent': 'var(--event-training-map-accent)',
          'seminar-bg': 'var(--event-seminar-bg)',
          'seminar-border': 'var(--event-seminar-border)',
          'seminar-text': 'var(--event-seminar-text)',
          'seminar-icon-bg': 'var(--event-seminar-icon-bg)',
          'seminar-icon-text': 'var(--event-seminar-icon-text)',
          'seminar-detail-border': 'var(--event-seminar-detail-border)',
          'seminar-meta-icon': 'var(--event-seminar-meta-icon)',
          'seminar-map-accent': 'var(--event-seminar-map-accent)',
          'etc-bg': 'var(--event-etc-bg)',
          'etc-border': 'var(--event-etc-border)',
          'etc-text': 'var(--event-etc-text)',
          'etc-icon-bg': 'var(--event-etc-icon-bg)',
          'etc-icon-text': 'var(--event-etc-icon-text)',
          'etc-detail-border': 'var(--event-etc-detail-border)',
          'etc-meta-icon': 'var(--event-etc-meta-icon)',
          'etc-map-accent': 'var(--event-etc-map-accent)',
          'match-bg': 'var(--event-match-bg)',
          'match-border': 'var(--event-match-border)',
          'match-text': 'var(--event-match-text)',
          'match-icon-bg': 'var(--event-match-icon-bg)',
          'match-icon-text': 'var(--event-match-icon-text)',
          'match-detail-border': 'var(--event-match-detail-border)',
          'match-meta-icon': 'var(--event-match-meta-icon)',
          'match-map-accent': 'var(--event-match-map-accent)',
          'vote-bg': 'var(--event-vote-bg)',
          'vote-border': 'var(--event-vote-border)',
          'vote-text': 'var(--event-vote-text)',
          'vote-icon-bg': 'var(--event-vote-icon-bg)',
          'vote-icon-text': 'var(--event-vote-icon-text)',
          'vote-detail-border': 'var(--event-vote-detail-border)',
          'vote-meta-icon': 'var(--event-vote-meta-icon)',
          'vote-map-accent': 'var(--event-vote-map-accent)',
        },
        stat: {
          diamond: 'var(--stat-diamond)',
          gold: 'var(--stat-gold)',
          silver: 'var(--stat-silver)',
          bronze: 'var(--stat-bronze)',
        },
        pos: {
          fw: 'var(--pos-fw)',
          mf: 'var(--pos-mf)',
          df: 'var(--pos-df)',
          gk: 'var(--pos-gk)',
        },
        chem: {
          strong: 'var(--chem-strong)',
          weak: 'var(--chem-weak)',
          neutral: 'var(--chem-neutral)',
        },
        stamina: {
          full: 'var(--stamina-full)',
          mid: 'var(--stamina-mid)',
          low: 'var(--stamina-low)',
        },
        foot: {
          active: 'var(--foot-active)',
          inactive: 'var(--foot-inactive)',
          stroke: 'var(--foot-stroke)',
        },
        viz: {
          primary: 'var(--viz-primary)',
          'primary-fill': 'var(--viz-primary-fill)',
          secondary: 'var(--viz-secondary)',
          'secondary-fill': 'var(--viz-secondary-fill)',
          tertiary: 'var(--viz-tertiary)',
          'tertiary-fill': 'var(--viz-tertiary-fill)',
          danger: 'var(--viz-danger)',
          'danger-fill': 'var(--viz-danger-fill)',
          grid: 'var(--viz-grid)',
          label: 'var(--viz-label)',
        },
        // 축구 소셜앱 메타포
        attend: {
          yes: 'var(--attend-yes)',
          maybe: 'var(--attend-maybe)',
          no: 'var(--attend-no)',
        },
        result: {
          win: 'var(--result-win)',
          draw: 'var(--result-draw)',
          loss: 'var(--result-loss)',
        },
        matchst: {
          upcoming: 'var(--match-upcoming)',
          live: 'var(--match-live)',
          completed: 'var(--match-completed)',
          cancelled: 'var(--match-cancelled)',
        },
        award: {
          mvp: 'var(--award-mvp)',
          motm: 'var(--award-motm)',
          assist: 'var(--award-assist)',
          goals: 'var(--award-goals)',
        },
        fee: {
          paid: 'var(--fee-paid)',
          unpaid: 'var(--fee-unpaid)',
          partial: 'var(--fee-partial)',
        },
        skill: {
          beginner: 'var(--skill-beginner)',
          intermediate: 'var(--skill-intermediate)',
          advanced: 'var(--skill-advanced)',
          pro: 'var(--skill-pro)',
        },
        trend: {
          up: 'var(--trend-up)',
          down: 'var(--trend-down)',
          flat: 'var(--trend-flat)',
        },
        highlight: {
          purple: 'var(--highlight-purple)',
          'purple-bg': 'var(--highlight-purple-bg)',
          amber: 'var(--highlight-amber)',
          'amber-bg': 'var(--highlight-amber-bg)',
          rose: 'var(--highlight-rose)',
          'rose-bg': 'var(--highlight-rose-bg)',
        },
        metric: {
          purple: 'var(--metric-purple)',
          'purple-bg': 'var(--metric-purple-bg)',
          orange: 'var(--metric-orange)',
          'orange-bg': 'var(--metric-orange-bg)',
          cyan: 'var(--metric-cyan)',
          'cyan-bg': 'var(--metric-cyan-bg)',
          gray: 'var(--metric-gray)',
          'gray-bg': 'var(--metric-gray-bg)',
        },
        social: {
          like: 'var(--social-like)',
          reply: 'var(--social-reply)',
          mention: 'var(--social-mention)',
        },
        glass: {
          bg: 'var(--glass-bg)',
          'bg-hover': 'var(--glass-bg-hover)',
          border: 'var(--glass-border)',
          'border-hover': 'var(--glass-border-hover)',
          shadow: 'var(--glass-shadow)',
        },
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '100%': { transform: 'translateX(100%)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(100%)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.3s ease-in-out',
        shimmer: 'shimmer 2s infinite',
        slideUp: 'slideUp 0.3s ease-out',
        slideInRight: 'slideInRight 0.25s ease-out',
      }
    },
  },
  plugins: [],
};
export default config;
